---
title: "Close the Gap #0: Geodata - Berlin Base"
output: html_notebook
---

## Load the packages

```{r}
source("000_setup.R")
```

## Berlin

> TODO: From City Lab Berlin

```{r}
berlin_bezirke_sf <- geojsonsf::geojson_sf("geodata/bezirksgrenzen.geojson")

plot(berlin_bezirke_sf[1])
```

```{r}
berlin_sf <- berlin_bezirke_sf %>% st_union()

plot(berlin_sf[1])
```

```{r}
berlin_strassen_sf <- geojsonsf::geojson_sf("geodata/Detailnetz-Strassenabschnitte.geojson")
plot(berlin_strassen_sf[1])
```

> 45K Streets; maybe caution on low-RAM systems

```{r fig.width=10, fig.height=8, eval=FALSE}
ggplot() +
  # geom_sf(data = berlin_strassen_sf, fill = NA) +
  geom_sf(data = berlin_bezirke_sf, fill = NA, color = "red") +
  geom_sf(data = berlin_strassen_sf,
          aes(color = STRKLASSE),
          size = 0.1) +
  theme_void() + 
  theme(panel.background = element_rect(fill = "black"),
        legend.position = "none")
```

```{r eval=FALSE}
mapdeck(style = mapdeck_style("dark")) %>% 
  mapdeck::add_sf(berlin_strassen_sf, stroke_colour = "STRKLASSE")
```


```{r}
sessionInfo()
```

